### ISSUE TITLE
Question if it's ok?

### ISSUE THREAD

**Issue by NorseXMB** [DizzRL/ps4-bo3-gsc-injector#4]
Hello, So I was curious, how long is the process and what are the requirements to add 7.55 support to a mod tool? I was wanting to start making Programs and not sure how to add support for newer Jailbreaks in any programs, and will this be the same process for adding multiple Firmware support in a program?

Thank you in Advance!

**Comment by someguythatmods** [comment]
Hey! Check out branch [feature/standalone-with-755-support](https://github.com/DizzRL/ps4-bo3-gsc-injector/tree/feature/standalone-with-755-support) I have added 7.55 support (Just haven't merged or released it yet). The process would basically be add payload injection to your tool, and make sure your tool includes payloads for each version you would like to support, and have a selector so that you can inject the correct payload.

**Comment by NorseXMB** [comment]
Awesome, thank you!
